### ISSUE TITLE
Меняем метку в yml

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#661]
Меняем UTM метку в yml который отдается яндекс маркету https://www.shopelectro.ru/static/yandex.yml
напоминаю, что от этого фаила зависят и другие yml. в них не меняем.

<url>https://www.shopelectro.ru/catalog/products/4023/?utm_source=YM&amp;utm_medium=cpc&amp;utm_content=akkumuliatory-270&amp;utm_term=4023</url>

utm_medium=cpc нужно сменить на utm_medium=cpc-market

**Comment by duker33** [comment]
i'll fix it in two iterations:
- fast and dirty hack for production
- good code with tests and review

**Comment by duker33** [comment]
done fast fix at https://github.com/fidals/shopelectro/pull/657

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#666](https://github.com/fidals/shopelectro/issues/666), [#667](https://github.com/fidals/shopelectro/issues/667) are still not solved.

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#666](https://github.com/fidals/shopelectro/issues/666), [#679](https://github.com/fidals/shopelectro/issues/679) are still not solved; solved: [#667](https://github.com/fidals/shopelectro/issues/667).

**Comment by 0pdd** [comment]
@themygit the puzzle [#666](https://github.com/fidals/shopelectro/issues/666) is still not solved; solved: [#667](https://github.com/fidals/shopelectro/issues/667), [#679](https://github.com/fidals/shopelectro/issues/679).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#714](https://github.com/fidals/shopelectro/issues/714), [#715](https://github.com/fidals/shopelectro/issues/715) are still not solved; solved: [#666](https://github.com/fidals/shopelectro/issues/666), [#667](https://github.com/fidals/shopelectro/issues/667), [#679](https://github.com/fidals/shopelectro/issues/679).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#714](https://github.com/fidals/shopelectro/issues/714), [#721](https://github.com/fidals/shopelectro/issues/721) are still not solved; solved: [#666](https://github.com/fidals/shopelectro/issues/666), [#667](https://github.com/fidals/shopelectro/issues/667), [#679](https://github.com/fidals/shopelectro/issues/679), [#715](https://github.com/fidals/shopelectro/issues/715).
